Traceback (most recent call last):
  File "main.py", line 31, in <module>
    main()
  File "main.py", line 21, in main
    model = net.ehrEncoding(len(data), len(data[0][0]), model_pars['embedding_dim'], model_pars['kernel_size'])
  File "/data1/users/isotta/complex_disorders/bin/model/net.py", line 25, in __init__
    self.linear2 = nn.Linear(64, vocab_size*max_seq_len)
  File "/data1/users/isotta/multMyeloma/bin_pytorch/dl4ehr/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 46, in __init__
    self.reset_parameters()
  File "/data1/users/isotta/multMyeloma/bin_pytorch/dl4ehr/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 50, in reset_parameters
    self.weight.data.uniform_(-stdv, stdv)
KeyboardInterrupt
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCTensorRandom.cu line=25 error=2 : out of memory
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    main()
  File "main.py", line 22, in main
    model = nn.DataParallel(model, device_ids=[1,2,3])
  File "/data1/users/isotta/multMyeloma/bin_pytorch/dl4ehr/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 102, in __init__
    _check_balance(self.device_ids)
  File "/data1/users/isotta/multMyeloma/bin_pytorch/dl4ehr/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 17, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/data1/users/isotta/multMyeloma/bin_pytorch/dl4ehr/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 17, in <listcomp>
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/data1/users/isotta/multMyeloma/bin_pytorch/dl4ehr/lib/python3.5/site-packages/torch/cuda/__init__.py", line 290, in get_device_properties
    init()  # will define _get_device_properties and _CudaDeviceProperties
  File "/data1/users/isotta/multMyeloma/bin_pytorch/dl4ehr/lib/python3.5/site-packages/torch/cuda/__init__.py", line 143, in init
    _lazy_init()
  File "/data1/users/isotta/multMyeloma/bin_pytorch/dl4ehr/lib/python3.5/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/THCTensorRandom.cu:25
